### ISSUE TITLE
rule: filters の実装

### ISSUE THREAD

**Issue by ShotaKitazawa** [ShotaKitazawa/etcd-injector#4]
rules.yaml に以下のように書くと inject を行う対象を filtering することが出来るようにする

```yaml
- jsonpath: ".value"
  repl: "replaced"
  filters:
  # 複数の filter rule の AND を取る
  - "Exist=.*"        # key が正規表現に match するもののみ置換の対象にする
  - "NotExist=.*"     # key が正規表現に match しないもののみ置換の対象にする
  - "Equal=key=.*"    # value が正規表現に match するもののみ置換の対象にする
  - "NotEqual=key=.*" # value が正規表現に match しないもののみ置換の対象にする
```
